# Generated by Django 6.0.7 on 2026-09-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_recompensa_alter_publicacion_contacto_and_more'),
        ('ubicaciones', '0003_region_remove_comuna_ciudad_comuna_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='ubicaciones.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='ubicaciones.sector'),
        ),
    ]
