import { EstadoPublicacion, type PublicacionConCategoria } from "./types";

export type PublicacionRecienteMock = PublicacionConCategoria;

export const publicacionesRecientesMock: PublicacionRecienteMock[] = [
  {
    categoriaSlug: "compra-y-venta",
    publicacion: {
      id: 1,
      titulo: "Bicicleta aro 26 en buen estado",
      slug: "bicicleta-aro-26-en-buen-estado",
      descripcion: "Bicicleta usada, poco uso, frenos nuevos.",
      categoria: 1,
      categoria_nombre: "Compra y venta",
      subcategoria: null,
      subcategoria_nombre: null,
      precio: "45000",
      estado: EstadoPublicacion.Disponible,
      ubicacion: 1,
      ubicacion_nombre: "Melipilla centro",
      usuario: 1,
      usuario_nombre: "camila",
      fecha_publicacion: "2026-09-18T12:00:00Z",
      fecha_expiracion: null,
      contacto: "+56 9 1234 5678",
      imagenes: [],
    },
  },
  {
    categoriaSlug: "arriendos-y-propiedades",
    publicacion: {
      id: 2,
      titulo: "Arriendo pieza amoblada cerca del centro",
      slug: "arriendo-pieza-amoblada-cerca-del-centro",
      descripcion: "Pieza amoblada, baño compartido, incluye wifi.",
      categoria: 2,
      categoria_nombre: "Arriendos y propiedades",
      subcategoria: null,
      subcategoria_nombre: null,
      precio: "180000",
      estado: EstadoPublicacion.Disponible,
      ubicacion: 1,
      ubicacion_nombre: "Melipilla centro",
      usuario: 2,
      usuario_nombre: "jorge",
      fecha_publicacion: "2026-09-18T09:30:00Z",
      fecha_expiracion: null,
      contacto: "jorge@example.com",
      imagenes: [],
    },
  },
  // {
  //   categoriaSlug: "empleos",
  //   publicacion: {
  //     id: 3,
  //     titulo: "Se busca ayudante de bodega",
  //     slug: "se-busca-ayudante-de-bodega",
  //     descripcion: "Jornada completa, experiencia no excluyente.",
  //     categoria: 5,
  //     categoria_nombre: "Empleos",
  //     subcategoria: null,
  //     subcategoria_nombre: null,
  //     precio: null,
  //     estado: EstadoPublicacion.Disponible,
  //     ubicacion: 2,
  //     ubicacion_nombre: "San Manuel",
  //     usuario: 3,
  //     usuario_nombre: "distribuidora-mp",
  //     fecha_publicacion: "2026-09-17T16:45:00Z",
  //     fecha_expiracion: null,
  //     contacto: "+56 9 8765 4321",
  //     imagenes: [],
  //   },
  // },
  // {
  //   categoriaSlug: "perdidos-y-encontrados",
  //   publicacion: {
  //     id: 4,
  //     titulo: "Se perdió gato color negro sector Las Palmas",
  //     slug: "se-perdio-gato-color-negro-sector-las-palmas",
  //     descripcion: "Responde al nombre de Michi, es muy tímido.",
  //     categoria: 8,
  //     categoria_nombre: "Perdidos y encontrados",
  //     subcategoria: null,
  //     subcategoria_nombre: null,
  //     precio: null,
  //     estado: EstadoPublicacion.Disponible,
  //     ubicacion: 3,
  //     ubicacion_nombre: "Las Palmas",
  //     usuario: 4,
  //     usuario_nombre: "valentina",
  //     fecha_publicacion: "2026-09-17T08:15:00Z",
  //     fecha_expiracion: null,
  //     contacto: "+56 9 2222 3333",
  //     imagenes: [],
  //   },
  // },
];
