# Generated by Django 6.0.7 on 2026-09-25 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_initial'),
        ('ubicaciones', '0002_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='recompensa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo / Vigente'), ('pausado', 'Pausado'), ('resuelto', 'Resuelto / Terminado'), ('expirado', 'Expirado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='ubicaciones.sector'),
        ),
    ]
