# Generated by Django 6.1.1 on 2026-10-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, choices=[('home', 'Casa'), ('shopping-bag', 'Bolsa de compras'), ('car', 'Auto'), ('briefcase', 'Maletín'), ('wrench', 'Llave inglesa'), ('party-popper', 'Fiesta'), ('paw-print', 'Huella de mascota'), ('search', 'Lupa'), ('tag', 'Etiqueta'), ('megaphone', 'Megáfono'), ('newspaper', 'Periódico'), ('sparkles', 'Destellos')], help_text='Ícono mostrado en el frontend (lucide-react).', max_length=50),
        ),
    ]
