# Generated by Django 6.0.7 on 2026-09-25 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='ubicaciones.comuna')),
            ],
            options={
                'verbose_name': 'Sector / Barrio',
                'verbose_name_plural': 'Sectores / Barrios',
                'ordering': ['nombre'],
            },
        ),
    ]
