# Generated by Django 6.0.7 on 2026-09-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_romano', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='ubicaciones.region'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
